/**
 * 旅遊資訊API
 * 本開放資料平台透過swagger套件提供。<br />                              如需要更詳盡的資料開放訊息，請至 <a href=\"https://data.taipei\" target=\"_blank\" title=\"臺北市政府開放資料平台\">臺北市政府開放資料平台</a>。
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Link } from './link';


/**
 * 活動展演
 */
export interface Activity { 
    /**
     * 活動地點行政區
     */
    distric?: string;
    /**
     * 活動地址
     */
    address?: string;
    /**
     * 活動地點緯度(WGS84)
     */
    nlat?: string;
    /**
     * 活動地點經度(WGS84)
     */
    elong?: string;
    /**
     * 主辦單位
     */
    organizer?: string;
    /**
     * 協辦單位
     */
    coRganizer?: string;
    /**
     * 聯絡人
     */
    contact?: string;
    /**
     * 連絡電話
     */
    tel?: string;
    /**
     * 傳真電話
     */
    fax?: string;
    /**
     * 門票/收費資訊
     */
    ticket?: string;
    /**
     * 交通資訊
     */
    traffic?: string;
    /**
     * 停車資訊
     */
    parking?: string;
    /**
     * 編號
     */
    id?: number;
    /**
     * 標題
     */
    title?: string;
    /**
     * 內容
     */
    description?: string;
    /**
     * 資訊有效開始時間
     */
    begin?: Date;
    /**
     * 資訊有效結束時間
     */
    end?: Date;
    /**
     * 發佈時間
     */
    posted?: Date;
    /**
     * 最後修改時間
     */
    modified?: Date;
    /**
     * 資料源網址
     */
    url?: string;
    /**
     * 相關附件
     */
    files?: Array<any>;
    /**
     * 相關連結
     */
    links?: Array<Link>;
}
