/**
 * 旅遊資訊API
 * 本開放資料平台透過swagger套件提供。<br />                              如需要更詳盡的資料開放訊息，請至 <a href=\"https://data.taipei\" target=\"_blank\" title=\"臺北市政府開放資料平台\">臺北市政府開放資料平台</a>。
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Category } from './category';
import { Image } from './image';
import { Link } from './link';


/**
 * 熱門景點
 */
export interface Attraction { 
    /**
     * 編號
     */
    id?: number;
    /**
     * 標題
     */
    name?: string;
    /**
     * 標題
     */
    nameZh?: string;
    /**
     * 標題
     */
    openStatus?: number;
    /**
     * 介紹
     */
    introduction?: string;
    /**
     * 開放時間
     */
    openTime?: string;
    /**
     * 郵遞區號
     */
    zipcode?: string;
    /**
     * 行政區
     */
    distric?: string;
    /**
     * 地址
     */
    address?: string;
    /**
     * 電話
     */
    tel?: string;
    /**
     * 傳真
     */
    fax?: string;
    /**
     * 電子郵件
     */
    email?: string;
    /**
     * 月份
     */
    months?: string;
    /**
     * 北緯
     */
    nlat?: number;
    /**
     * 東經
     */
    elong?: number;
    /**
     * 官方網站網址
     */
    officialSite?: string;
    /**
     * 臉書粉絲頁網址
     */
    facebook?: string;
    /**
     * 門票/收費
     */
    ticket?: string;
    /**
     * 旅遊叮嚀
     */
    remind?: string;
    /**
     * 停留時間
     */
    staytime?: string;
    /**
     * 最後修改時間
     */
    modified?: Date;
    /**
     * 資料源網址
     */
    url?: string;
    /**
     * 主題分類
     */
    category?: Array<Category>;
    /**
     * 對象
     */
    target?: Array<Category>;
    /**
     * 服務設施
     */
    service?: Array<Category>;
    /**
     * 友善服務
     */
    friendly?: Array<Category>;
    /**
     * 相關圖片
     */
    images?: Array<Image>;
    /**
     * 相關附件
     */
    files?: Array<any>;
    /**
     * 相關連結
     */
    links?: Array<Link>;
}
