/**
 * 旅遊資訊API
 * 本開放資料平台透過swagger套件提供。<br />                              如需要更詳盡的資料開放訊息，請至 <a href=\"https://data.taipei\" target=\"_blank\" title=\"臺北市政府開放資料平台\">臺北市政府開放資料平台</a>。
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Link } from './link';


/**
 * 新聞
 */
export interface News { 
    /**
     * 編號
     */
    id?: number;
    /**
     * 標題
     */
    title?: string;
    /**
     * 內容
     */
    description?: string;
    /**
     * 資訊有效開始時間
     */
    begin?: Date;
    /**
     * 資訊有效結束時間
     */
    end?: Date;
    /**
     * 發佈時間
     */
    posted?: Date;
    /**
     * 最後修改時間
     */
    modified?: Date;
    /**
     * 資料源網址
     */
    url?: string;
    /**
     * 相關附件
     */
    files?: Array<any>;
    /**
     * 相關連結
     */
    links?: Array<Link>;
}
