/**
 * 旅遊資訊API
 * 本開放資料平台透過swagger套件提供。<br />                              如需要更詳盡的資料開放訊息，請至 <a href=\"https://data.taipei\" target=\"_blank\" title=\"臺北市政府開放資料平台\">臺北市政府開放資料平台</a>。
 *
 * OpenAPI spec version: V1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Category } from './category';


/**
 * 遊程
 */
export interface Tour { 
    iDkBackingField?: number;
    seasonsRawkBackingField?: string;
    monthsRawkBackingField?: string;
    seasonskBackingField?: Array<string>;
    monthskBackingField?: Array<string>;
    dayskBackingField?: number;
    titlekBackingField?: string;
    authorkBackingField?: string;
    descriptionkBackingField?: string;
    consumekBackingField?: string;
    remarkkBackingField?: string;
    notekBackingField?: string;
    urlkBackingField?: string;
    categorykBackingField?: Array<Category>;
    transportkBackingField?: Array<Category>;
    userskBackingField?: Array<Category>;
    modifiedkBackingField?: Date;
    fileskBackingField?: Array<any>;
}
